version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
       MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/vols/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
        - cluster.name=search-cluster
